<?php
namespace oppo\service\alert;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface AlertUtilitiesServiceIf {
  /**
   * @param string[] $to
   * @param string[] $cc
   * @param string $subject
   * @param string $content
   * @param string $attach
   * @param string $attachTitle
   */
  public function SendEmail(array $to, array $cc, $subject, $content, $attach, $attachTitle);
  /**
   * @param string[] $to
   * @param string[] $cc
   * @param string $subject
   * @param string $content
   * @param string $attach
   * @param string $attachTitle
   */
  public function SendHTMLEmail(array $to, array $cc, $subject, $content, $attach, $attachTitle);
  /**
   * @param string[] $to
   * @param string $content
   * @param string $template
   */
  public function SendSMS(array $to, $content, $template);
  /**
   * @param string[] $to
   * @param string $content
   * @param string $template
   */
  public function SendWxNotice(array $to, $content, $template);
  /**
   * @return int
   */
  public function GetNowTime();
  /**
   * @return string
   */
  public function PrintVersion();
}


